# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Setup
title:               GT
tagline:             'Pure Technical'
description:         'Keep simple.'
url:                 http://geteng.xyz
baseurl:             ''
paginate:            5
excerpt_separator:   <!--more-->
markdown:            kramdown

# About/contact
author:
  name:              GeTeng
  url:               http://geteng.xyz
  email:             md5sum@icloud.com

version:             1.0.0
github:
  repo:              https://github.com/tengg/tengg.github.io

gems:
  - jekyll-sitemap
  - kramdown
