# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Setup
title:               GT
tagline:             'Pure technical'
description:         'Keep simple. Hosted by <a href="https://ca.linkedin.com/in/tengg
" target="_blank">Teng<img src="https://static.licdn.com/scds/common/u/img/webpromo/btn_in_20x15.png" style="display: inline; margin: 2px;"></a>'
url:                 http://geteng.xyz
baseurl:             ''
paginate:            5
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              GeTeng
  url:               http://geteng.xyz
  email:             md5sum@icloud.com

version:             1.0.0
